version: "3.9"

services:
  ezbill-api:
    build:
      context: .
      dockerfile: EzBill/Dockerfile
    image: ezbill-api:latest
    container_name: ezbill-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=ezbill-db;Port=5432;Database=ezbill_db;Username=postgres;Password=paavag2481L@
      - MongoDbSettings__ConnectionString=mongodb://ezbill-mongo:27017
      - MongoDbSettings__Database=ezbill_mongo
    depends_on:
      - ezbill-db
      - ezbill-mongo

  ezbill-db:
    image: postgres:15-alpine
    container_name: ezbill-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: paavag2481L@
      POSTGRES_DB: ezbill_db
    ports:
      - "5432:5432"
    volumes:
      - ezbill_pgdata:/var/lib/postgresql/data

  ezbill-mongo:
    image: mongo:6.0
    container_name: ezbill-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ezbill_mongo_data:/data/db

volumes:
  ezbill_pgdata:
  ezbill_mongo_data:
