version: "3.9"

services:
  ezbill-api:
    build:
      context: .
      dockerfile: EzBill/Dockerfile
    image: ezbill-api:latest
    container_name: ezbill-api
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=ezbill-db;Port=5432;Database=ezbill_db;Username=postgres;Password=yourpassword
    depends_on:
      - ezbill-db

  ezbill-db:
    image: postgres:15-alpine
    container_name: ezbill-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ezbill_db
    ports:
      - "5432:5432"
    volumes:
      - ezbill_pgdata:/var/lib/postgresql/data

volumes:
  ezbill_pgdata:
