version: "3.9"

services:
  ezbill-api:
    build:
      context: .
      dockerfile: EzBill/Dockerfile
    image: ezbill-api:latest
    container_name: ezbill-api
    ports:
      - "5000:80"
    env_file:
      - .env
    depends_on:
      - ezbill-db

  ezbill-db:
    image: postgres:15-alpine
    container_name: ezbill-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ezbill_pgdata:/var/lib/postgresql/data

  

volumes:
  ezbill_pgdata:
